# Generated by Django 4.2.5 on 2024-01-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_alternative_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='g_percentag',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='g_yop',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='intr_percentag',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='intr_yop',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ssc_percentag',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ssc_yop',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
