# Generated by Django 4.2.5 on 2024-01-04 09:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_student_g_percentag_alter_student_g_yop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mockinterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('present', models.BooleanField(default=False, null=True)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MaxValueValidator(100)])),
                ('max_marks', models.DecimalField(decimal_places=2, default=10, max_digits=8, validators=[django.core.validators.MaxValueValidator(100)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentuser')),
            ],
        ),
    ]
