# Generated by Django 4.2.5 on 2024-01-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mockinterview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockinterview',
            old_name='test_date',
            new_name='date',
        ),
    ]
