# Generated by Django 4.2.5 on 2024-01-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_test_date_mockinterview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
