# Generated by Django 4.2.5 on 2024-01-05 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_test_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
