# Generated by Django 4.2.5 on 2024-01-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_test_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='name',
            field=models.CharField(default='vcube', max_length=40),
        ),
    ]
