# Generated by Django 4.2.5 on 2024-01-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_studentuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='present',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
