# Generated by Django 4.2.5 on 2024-01-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_studentuser_actual_fees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='interview_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='max_marks',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='max_performance',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='performance',
        ),
        migrations.AddField(
            model_name='interview',
            name='company_name',
            field=models.CharField(default='company_name', max_length=200),
        ),
    ]
