# Generated by Django 4.2.5 on 2024-01-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_interview_date_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='student_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='None', max_length=20),
        ),
    ]
